merge main & add print sink

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -7,7 +7,8 @@ extend = [
   { path = "src/risedevtool/kafka.toml" },
   { path = "src/risedevtool/redis.toml" },
   { path = "src/risedevtool/risedev-components.toml" },
-  { path = "src/frontend/test_runner/planner_test.toml" },
+  { path = "src/frontend/planner_test/planner_test.toml" },
+  { path = "src/tests/compaction_test/Makefile.toml" },
 ]
 
 env_files = ["./risedev-components.user.env"]
@@ -22,7 +23,7 @@ is_all_in_one_enabled = get_env ENABLE_ALL_IN_ONE
 if ${is_sanitizer_enabled}
   set_env RISEDEV_CARGO_BUILD_EXTRA_ARGS "-Zbuild-std --target ${CARGO_MAKE_RUST_TARGET_TRIPLE}"
   set_env RISEDEV_BUILD_TARGET_DIR "${CARGO_MAKE_RUST_TARGET_TRIPLE}/"
-  set_env RISEDEV_RUSTFLAGS "--cfg tokio_unstable -Zsanitizer=thread"
+  set_env RISEDEV_RUSTFLAGS "-Ctarget-cpu=native --cfg tokio_unstable -Zsanitizer=thread"
 else
   set_env RISEDEV_CARGO_BUILD_EXTRA_ARGS ""
   set_env RISEDEV_BUILD_TARGET_DIR ""
@@ -59,6 +60,7 @@ script = '''
 rm -rf "${PREFIX_DATA}"
 rm -rf "${PREFIX_LOG}"
 rm -rf "${PREFIX_CONFIG}"
+rm -rf "${PREFIX_PROFILING}"
 '''
 
 
@@ -111,12 +113,23 @@ if (( "$(du -sk ${PREFIX_LOG} | cut -f1)" > 2000 )) ; then
 fi
 '''
 
+[tasks.doc]
+category = "Misc"
+description = "Open rustdoc for risingwave"
+dependencies = ["build-docs"]
+script = '''
+#!/bin/bash
+set -e
+
+python -mwebbrowser file://$(pwd)/target/doc/index.html
+'''
+
 [tasks.link-standalone-binaries]
 category = "RiseDev - Build"
 description = "Link standalone cmds to RiseDev bin"
 condition = { env_not_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -f "${PREFIX_BIN}/compute-node"
 rm -f "${PREFIX_BIN}/meta-node"
@@ -133,7 +146,7 @@ category = "RiseDev - Build"
 description = "Link all-in-one cmds to RiseDev bin"
 condition = { env_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_BIN}/risingwave"
@@ -151,7 +164,7 @@ category = "RiseDev - Build"
 description = "Link all binaries to .bin"
 condition = { env_set = ["ENABLE_ALL_IN_ONE"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_USR_BIN}"
@@ -184,7 +197,7 @@ category = "RiseDev - Build"
 description = "Extract dashboard artifact"
 condition = { env_not_set = ["ENABLE_BUILD_DASHBOARD_V2"] }
 script = '''
-#!@shell
+#!/bin/bash
 
 # we allow this script to fail
 
@@ -200,7 +213,7 @@ category = "RiseDev - Build"
 description = "Build dashboard v2"
 condition = { env_set = ["ENABLE_BUILD_DASHBOARD_V2"] }
 script = """
-#!@shell
+#!/bin/bash
 set -e
 
 rm -rf "${PREFIX_UI}"
@@ -231,7 +244,7 @@ category = "RiseDev - Build"
 description = "Clean Rust targets"
 condition = { env_set = ["ENABLE_BUILD_RUST"] }
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 cargo clean
 '''
@@ -240,8 +253,9 @@ cargo clean
 category = "RiseDev - Build"
 description = "Build Rust docs"
 condition = { env_set = ["ENABLE_BUILD_RUST"] }
+env = { RUSTDOCFLAGS = "--markdown-css ../../docs/rust.css --markdown-no-toc --index-page docs/index.md -Zunstable-options" }
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -252,7 +266,7 @@ cargo doc --workspace --no-deps --document-private-items
 category = "RiseDev - Prepare"
 description = "Copy necessary configuration files to RiseDev"
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -301,7 +315,7 @@ alias = "playground"
 category = "RiseDev - Start"
 description = "Start a lite RisingWave playground using risingwave all-in-one binary"
 script = '''
-#!@shell
+#!/bin/bash
 
 set -e
 
@@ -316,7 +330,7 @@ RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin risingwave --profile "${RISI
 category = "RiseDev - Start"
 description = "Start RiseCtl"
 script = '''
-#!@shell
+#!/bin/bash
 
 RC_ENV_FILE="${PREFIX_CONFIG}/risectl-env"
 
@@ -372,11 +386,11 @@ dependencies = ["k", "clean-data"]
 [tasks.install-tools]
 category = "RiseDev - Check"
 script = """
-#!@shell
+#!/bin/bash
 
 set -e
 
-for tool in cargo-llvm-cov cargo-nextest cargo-udeps cargo-hakari cargo-sort cargo-make
+for tool in cargo-llvm-cov cargo-nextest cargo-udeps cargo-hakari cargo-sort cargo-make typos-cli
 do
   echo "install: $(tput setaf 4)$tool$(tput sgr0)"
   cargo install $tool --locked
@@ -438,7 +452,7 @@ description = "Run unit tests"
 category = "RiseDev - Build in simulation mode"
 description = "Build in simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
@@ -482,11 +496,40 @@ cargo nextest run \
   "$@"
 """
 
+[tasks.sscale-test]
+category = "RiseDev - Simulation scaling tests"
+description = "Run integration scaling tests in deterministic simulation mode"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+script = """
+#!/bin/bash
+set -e
+
+cargo nextest run \
+  -p risingwave_simulation_scale \
+  "$@"
+"""
+
+[tasks.sarchive-scale-test]
+category = "RiseDev - Simulation scaling tests"
+description = "Archive integration scaling tests in deterministic simulation mode"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+script = """
+#!/bin/bash
+set -e
+
+cargo nextest archive \
+  -p risingwave_simulation_scale \
+  --archive-file scale-test.tar.zst \
+  "$@"
+"""
+
 [tasks.sslt]
 category = "RiseDev - Deterministic Simulation End-to-end Test"
 description = "Run e2e tests in deterministic simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
@@ -494,11 +537,23 @@ set -e
 cargo run -p risingwave_simulation "$@"
 """
 
+[tasks.sslt-cov]
+category = "RiseDev - Deterministic Simulation End-to-end Test"
+description = "Run e2e tests in deterministic simulation mode and report code coverage"
+dependencies = ["warn-on-missing-tools"]
+env = { RUSTFLAGS = "-Ctarget-cpu=native --cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim-cov" }
+script = """
+#!/bin/bash
+set -e
+
+cargo llvm-cov run -p risingwave_simulation --html "$@"
+"""
+
 [tasks.check-hakari]
 category = "RiseDev - Check"
 description = "Run cargo hakari check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo hakari$(tput sgr0) checks and attempting to fix"
 
@@ -512,7 +567,7 @@ test $? -eq 0 || exit 1
 category = "RiseDev - Check"
 description = "Run cargo sort check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo sort$(tput sgr0) checks and attempting to fix"
 
@@ -525,7 +580,7 @@ test $? -eq 0 || { echo "cargo sort check failed. You may run $(tput setaf 4)car
 category = "RiseDev - Check"
 description = "Run cargo fmt check and attempt to fix"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo fmt$(tput sgr0) checks and attempting to fix"
 cargo fmt --all
@@ -536,12 +591,27 @@ test $? -eq 0 || exit 1
 category = "RiseDev - Check"
 description = "Run cargo clippy check"
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Running $(tput setaf 4)cargo clippy$(tput sgr0) checks"
-cargo clippy --all-targets --features failpoints
+cargo clippy --all-targets --all-features
 echo "If cargo clippy check failed or generates warning, you may run $(tput setaf 4)cargo clippy --workspace --all-targets --fix$(tput sgr0) to fix it. Note that clippy fix requires manual review, as not all auto fixes are guaranteed to be reasonable."
 """
+
+[tasks.check-typos]
+category = "RiseDev - Check"
+description = "Run cargo typos-cli check"
+script = """
+#!/bin/bash
+if ! [ -x "$(command -v typos)" ]; then
+  echo "Error: 'typos-cli' is not installed, please run './risedev install-tools'." >&2
+  exit 1
+fi
+if ! typos ; then
+  echo "Hint: use 'typos -w' to fix."
+fi
+"""
+
 
 [tasks.check]
 category = "RiseDev - Check"
@@ -551,9 +621,10 @@ dependencies = [
   "check-dep-sort",
   "check-fmt",
   "check-clippy",
+  "check-typos",
 ]
 script = """
-#!@shell
+#!/bin/bash
 
 echo "Good work! You may run $(tput setaf 4)./risedev test$(tput sgr0) or $(tput setaf 4)./risedev test-cov$(tput sgr0) to run unit tests."
 """
@@ -608,19 +679,47 @@ description = "Kill cluster, dump logs and check logs"
 [tasks.slt]
 category = "RiseDev - SQLLogicTest"
 dependencies = ["warn-on-missing-tools"]
-script = """
+command = "sqllogictest"
+args = ["${@}"]
+description = "Run SQLLogicTest"
+
+[tasks.slt-streaming]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/streaming/**/*.slt"]
+description = "Run all streaming e2e tests"
+
+[tasks.slt-batch]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/batch/**/*.slt"]
+description = "Run all batch e2e tests"
+
+[tasks.slt-generated]
+category = "RiseDev - SQLLogicTest"
+extend = "slt"
+args = ["${@}", "./e2e_test/generated/**/*.slt"]
+description = "Run all generated e2e tests"
+
+[tasks.slt-all]
+category = "RiseDev - SQLLogicTest"
+run_task = { name = ["slt-streaming", "slt-batch", "slt-generated"] }
+description = "Run all e2e tests"
+
+[tasks.docslt]
+category = "RiseDev - SQLLogicTest"
+description = "Extract SQL examples written in SQLLogicTest syntax from Rust doc comments"
+script = '''
 #!/bin/bash
 set -e
-
-sqllogictest "$@"
-"""
-description = "Run SQLLogicTest"
+cargo run --bin risedev-docslt -- "$@"
+'''
 
 [tasks.compose]
 category = "RiseDev - Compose"
 description = "Compose a docker-compose.yaml file"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -rf ${PREFIX_DOCKER}/*
 mkdir -p "${PREFIX_DOCKER}"
@@ -632,7 +731,7 @@ echo docker-compose file generated in $(tput setaf 4)${PREFIX_DOCKER}$(tput sgr0
 category = "RiseDev - Compose"
 description = "Compose a docker-compose.yaml deploy directory"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 rm -rf "${PREFIX_DOCKER}"/*
 mkdir -p "${PREFIX_DOCKER}"
@@ -645,7 +744,7 @@ echo If you are ready, run $(tput setaf 4)./risedev apply-compose-deploy$(tput s
 category = "RiseDev - Compose"
 description = "Run deploy.sh"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 .risingwave/rw-docker/deploy.sh "$@"
@@ -660,7 +759,7 @@ cat .risingwave/rw-docker/_message.partial.sh
 category = "RiseDev - Compose"
 description = "Run deploy.sh"
 script = '''
-#!@shell
+#!/bin/bash
 set -e
 
 cp -a .risingwave/rw-docker/* docker
